"""Added orm models

Revision ID: b2c788e7d096
Revises: 
Create Date: 2023-03-17 12:00:16.198730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c788e7d096'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('followers', 'who_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('followers', 'whom_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'followers', 'users', ['whom_id'], ['user_id'])
    op.create_foreign_key(None, 'followers', 'users', ['who_id'], ['user_id'])
    op.alter_column('latest', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('messages', 'message_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.create_foreign_key(None, 'messages', 'users', ['author_id'], ['user_id'])
    op.alter_column('users', 'user_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'user_id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.alter_column('messages', 'message_id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('latest', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.alter_column('followers', 'whom_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('followers', 'who_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
