{
 "title": "Minitwit responses",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request duration count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "minitwit_request_duration_milliseconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total http responses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "minitwit_http_responses_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request duration created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "minitwit_request_duration_milliseconds_created",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU load percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "minitwit_cpu_load_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request duration bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "minitwit_request_duration_milliseconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}